name: bucalscan_ai
description: "AI-powered oral lesion detection app for early cancer screening."
publish_to: 'none'

version: 1.2.3+7

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.4
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
