// Mocks generated by Mockito 5.4.6 from annotations
// in bucalscan_ai/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i18;

import 'package:bucalscan_ai/data/services/auth_storage_service.dart' as _i19;
import 'package:bucalscan_ai/features/admin/data/datasources/admin_remote_datasource.dart'
    as _i20;
import 'package:bucalscan_ai/features/admin/data/models/admin_request_models.dart'
    as _i4;
import 'package:bucalscan_ai/features/admin/data/models/admin_user_model.dart'
    as _i3;
import 'package:bucalscan_ai/features/admin/domain/entities/admin_query.dart'
    as _i2;
import 'package:bucalscan_ai/features/admin/domain/entities/admin_request.dart'
    as _i12;
import 'package:bucalscan_ai/features/admin/domain/entities/admin_user.dart'
    as _i11;
import 'package:bucalscan_ai/features/admin/domain/repositories/admin_repository.dart'
    as _i28;
import 'package:bucalscan_ai/features/admin/domain/usecases/get_admin_users_usecase.dart'
    as _i44;
import 'package:bucalscan_ai/features/admin/domain/usecases/update_admin_user_status_usecase.dart'
    as _i45;
import 'package:bucalscan_ai/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i17;
import 'package:bucalscan_ai/features/auth/domain/entities/auth_session.dart'
    as _i9;
import 'package:bucalscan_ai/features/auth/domain/entities/auth_user.dart'
    as _i10;
import 'package:bucalscan_ai/features/auth/domain/repositories/auth_repository.dart'
    as _i27;
import 'package:bucalscan_ai/features/auth/domain/usecases/get_cached_user_usecase.dart'
    as _i37;
import 'package:bucalscan_ai/features/auth/domain/usecases/get_current_user_usecase.dart'
    as _i36;
import 'package:bucalscan_ai/features/auth/domain/usecases/has_session_token_usecase.dart'
    as _i38;
import 'package:bucalscan_ai/features/auth/domain/usecases/login_usecase.dart'
    as _i34;
import 'package:bucalscan_ai/features/auth/domain/usecases/logout_usecase.dart'
    as _i39;
import 'package:bucalscan_ai/features/auth/domain/usecases/register_usecase.dart'
    as _i35;
import 'package:bucalscan_ai/features/dashboard/data/datasources/dashboard_remote_datasource.dart'
    as _i21;
import 'package:bucalscan_ai/features/dashboard/data/models/daily_summary_model.dart'
    as _i5;
import 'package:bucalscan_ai/features/dashboard/domain/entities/daily_summary.dart'
    as _i13;
import 'package:bucalscan_ai/features/dashboard/domain/repositories/dashboard_repository.dart'
    as _i29;
import 'package:bucalscan_ai/features/dashboard/domain/usecases/get_today_summary_usecase.dart'
    as _i41;
import 'package:bucalscan_ai/features/history/data/datasources/history_remote_datasource.dart'
    as _i22;
import 'package:bucalscan_ai/features/history/data/models/analysis_model.dart'
    as _i23;
import 'package:bucalscan_ai/features/history/data/models/history_page_model.dart'
    as _i6;
import 'package:bucalscan_ai/features/history/domain/entities/analysis.dart'
    as _i31;
import 'package:bucalscan_ai/features/history/domain/entities/history_query.dart'
    as _i14;
import 'package:bucalscan_ai/features/history/domain/repositories/history_repository.dart'
    as _i30;
import 'package:bucalscan_ai/features/history/domain/usecases/get_history_usecase.dart'
    as _i42;
import 'package:bucalscan_ai/features/prediction/data/datasources/prediction_remote_datasource.dart'
    as _i24;
import 'package:bucalscan_ai/features/prediction/data/models/prediction_result_model.dart'
    as _i7;
import 'package:bucalscan_ai/features/prediction/domain/entities/prediction_image_input.dart'
    as _i25;
import 'package:bucalscan_ai/features/prediction/domain/entities/prediction_result.dart'
    as _i15;
import 'package:bucalscan_ai/features/prediction/domain/repositories/prediction_repository.dart'
    as _i32;
import 'package:bucalscan_ai/features/prediction/domain/usecases/predict_image_usecase.dart'
    as _i43;
import 'package:bucalscan_ai/features/profile/data/datasources/profile_remote_datasource.dart'
    as _i26;
import 'package:bucalscan_ai/features/profile/data/models/user_profile_model.dart'
    as _i8;
import 'package:bucalscan_ai/features/profile/domain/entities/user_profile.dart'
    as _i16;
import 'package:bucalscan_ai/features/profile/domain/repositories/profile_repository.dart'
    as _i33;
import 'package:bucalscan_ai/features/profile/domain/usecases/update_profile_usecase.dart'
    as _i40;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAdminPage_0<T> extends _i1.SmartFake implements _i2.AdminPage<T> {
  _FakeAdminPage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminUserModel_1 extends _i1.SmartFake
    implements _i3.AdminUserModel {
  _FakeAdminUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminSummaryModel_2 extends _i1.SmartFake
    implements _i4.AdminSummaryModel {
  _FakeAdminSummaryModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminWorkspaceRequestModel_3 extends _i1.SmartFake
    implements _i4.AdminWorkspaceRequestModel {
  _FakeAdminWorkspaceRequestModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDailySummaryModel_4 extends _i1.SmartFake
    implements _i5.DailySummaryModel {
  _FakeDailySummaryModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHistoryPageModel_5 extends _i1.SmartFake
    implements _i6.HistoryPageModel {
  _FakeHistoryPageModel_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePredictionResultModel_6 extends _i1.SmartFake
    implements _i7.PredictionResultModel {
  _FakePredictionResultModel_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfileModel_7 extends _i1.SmartFake
    implements _i8.UserProfileModel {
  _FakeUserProfileModel_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthSession_8 extends _i1.SmartFake implements _i9.AuthSession {
  _FakeAuthSession_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthUser_9 extends _i1.SmartFake implements _i10.AuthUser {
  _FakeAuthUser_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminUser_10 extends _i1.SmartFake implements _i11.AdminUser {
  _FakeAdminUser_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminSummary_11 extends _i1.SmartFake implements _i12.AdminSummary {
  _FakeAdminSummary_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminWorkspaceRequest_12 extends _i1.SmartFake
    implements _i12.AdminWorkspaceRequest {
  _FakeAdminWorkspaceRequest_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDailySummary_13 extends _i1.SmartFake implements _i13.DailySummary {
  _FakeDailySummary_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHistoryPage_14 extends _i1.SmartFake implements _i14.HistoryPage {
  _FakeHistoryPage_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePredictionResult_15 extends _i1.SmartFake
    implements _i15.PredictionResult {
  _FakePredictionResult_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfile_16 extends _i1.SmartFake implements _i16.UserProfile {
  _FakeUserProfile_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i17.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<Map<String, dynamic>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i18.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i18.Future<Map<String, dynamic>>);

  @override
  _i18.Future<Map<String, dynamic>> register({
    required String? fullName,
    required String? doctorId,
    String? medicalCenter,
    required String? email,
    required String? password,
    required String? profession,
    String? specialty,
    String? workspaceChoice,
    String? workspaceId,
    String? workspaceName,
    String? workspaceType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #fullName: fullName,
              #doctorId: doctorId,
              #medicalCenter: medicalCenter,
              #email: email,
              #password: password,
              #profession: profession,
              #specialty: specialty,
              #workspaceChoice: workspaceChoice,
              #workspaceId: workspaceId,
              #workspaceName: workspaceName,
              #workspaceType: workspaceType,
            }),
            returnValue: _i18.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i18.Future<Map<String, dynamic>>);

  @override
  _i18.Future<Map<String, dynamic>> me() =>
      (super.noSuchMethod(
            Invocation.method(#me, []),
            returnValue: _i18.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i18.Future<Map<String, dynamic>>);
}

/// A class which mocks [AuthStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStorageService extends _i1.Mock
    implements _i19.AuthStorageService {
  MockAuthStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i18.Future<String?>.value(),
          )
          as _i18.Future<String?>);

  @override
  _i18.Future<void> removeToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeToken, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> saveUserJson(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserJson, [userData]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<Map<String, dynamic>?> getUserJson() =>
      (super.noSuchMethod(
            Invocation.method(#getUserJson, []),
            returnValue: _i18.Future<Map<String, dynamic>?>.value(),
          )
          as _i18.Future<Map<String, dynamic>?>);

  @override
  _i18.Future<void> removeUserJson() =>
      (super.noSuchMethod(
            Invocation.method(#removeUserJson, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [AdminRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminRemoteDataSource extends _i1.Mock
    implements _i20.AdminRemoteDataSource {
  MockAdminRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<List<_i3.AdminUserModel>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i18.Future<List<_i3.AdminUserModel>>.value(
              <_i3.AdminUserModel>[],
            ),
          )
          as _i18.Future<List<_i3.AdminUserModel>>);

  @override
  _i18.Future<_i2.AdminPage<_i3.AdminUserModel>> getUsersPage(
    _i2.AdminQuery? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersPage, [query]),
            returnValue: _i18.Future<_i2.AdminPage<_i3.AdminUserModel>>.value(
              _FakeAdminPage_0<_i3.AdminUserModel>(
                this,
                Invocation.method(#getUsersPage, [query]),
              ),
            ),
          )
          as _i18.Future<_i2.AdminPage<_i3.AdminUserModel>>);

  @override
  _i18.Future<_i2.AdminPage<_i4.AdminWorkspaceRequestModel>> getCentersPage(
    _i2.AdminQuery? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCentersPage, [query]),
            returnValue:
                _i18.Future<
                  _i2.AdminPage<_i4.AdminWorkspaceRequestModel>
                >.value(
                  _FakeAdminPage_0<_i4.AdminWorkspaceRequestModel>(
                    this,
                    Invocation.method(#getCentersPage, [query]),
                  ),
                ),
          )
          as _i18.Future<_i2.AdminPage<_i4.AdminWorkspaceRequestModel>>);

  @override
  _i18.Future<_i2.AdminPage<_i4.AdminMembershipRequestModel>> getAccessPage(
    _i2.AdminQuery? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAccessPage, [query]),
            returnValue:
                _i18.Future<
                  _i2.AdminPage<_i4.AdminMembershipRequestModel>
                >.value(
                  _FakeAdminPage_0<_i4.AdminMembershipRequestModel>(
                    this,
                    Invocation.method(#getAccessPage, [query]),
                  ),
                ),
          )
          as _i18.Future<_i2.AdminPage<_i4.AdminMembershipRequestModel>>);

  @override
  _i18.Future<_i3.AdminUserModel> updateUserStatus({
    required int? userId,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserStatus, [], {
              #userId: userId,
              #status: status,
            }),
            returnValue: _i18.Future<_i3.AdminUserModel>.value(
              _FakeAdminUserModel_1(
                this,
                Invocation.method(#updateUserStatus, [], {
                  #userId: userId,
                  #status: status,
                }),
              ),
            ),
          )
          as _i18.Future<_i3.AdminUserModel>);

  @override
  _i18.Future<_i4.AdminSummaryModel> getSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getSummary, []),
            returnValue: _i18.Future<_i4.AdminSummaryModel>.value(
              _FakeAdminSummaryModel_2(
                this,
                Invocation.method(#getSummary, []),
              ),
            ),
          )
          as _i18.Future<_i4.AdminSummaryModel>);

  @override
  _i18.Future<List<_i4.AdminWorkspaceRequestModel>> getWorkspaceRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceRequests, []),
            returnValue:
                _i18.Future<List<_i4.AdminWorkspaceRequestModel>>.value(
                  <_i4.AdminWorkspaceRequestModel>[],
                ),
          )
          as _i18.Future<List<_i4.AdminWorkspaceRequestModel>>);

  @override
  _i18.Future<List<_i4.AdminMembershipRequestModel>> getMembershipRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipRequests, []),
            returnValue:
                _i18.Future<List<_i4.AdminMembershipRequestModel>>.value(
                  <_i4.AdminMembershipRequestModel>[],
                ),
          )
          as _i18.Future<List<_i4.AdminMembershipRequestModel>>);

  @override
  _i18.Future<void> decideWorkspace(int? id, {required bool? approve}) =>
      (super.noSuchMethod(
            Invocation.method(#decideWorkspace, [id], {#approve: approve}),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i4.AdminWorkspaceRequestModel> updateCenter({
    required int? id,
    required String? city,
    required String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCenter, [], {
              #id: id,
              #city: city,
              #address: address,
            }),
            returnValue: _i18.Future<_i4.AdminWorkspaceRequestModel>.value(
              _FakeAdminWorkspaceRequestModel_3(
                this,
                Invocation.method(#updateCenter, [], {
                  #id: id,
                  #city: city,
                  #address: address,
                }),
              ),
            ),
          )
          as _i18.Future<_i4.AdminWorkspaceRequestModel>);

  @override
  _i18.Future<void> decideMembership(
    int? id, {
    required bool? approve,
    String? role = 'professional',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #decideMembership,
              [id],
              {#approve: approve, #role: role},
            ),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [DashboardRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRemoteDataSource extends _i1.Mock
    implements _i21.DashboardRemoteDataSource {
  MockDashboardRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i5.DailySummaryModel> getTodaySummary() =>
      (super.noSuchMethod(
            Invocation.method(#getTodaySummary, []),
            returnValue: _i18.Future<_i5.DailySummaryModel>.value(
              _FakeDailySummaryModel_4(
                this,
                Invocation.method(#getTodaySummary, []),
              ),
            ),
          )
          as _i18.Future<_i5.DailySummaryModel>);
}

/// A class which mocks [HistoryRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRemoteDataSource extends _i1.Mock
    implements _i22.HistoryRemoteDataSource {
  MockHistoryRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<List<_i23.AnalysisModel>> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: _i18.Future<List<_i23.AnalysisModel>>.value(
              <_i23.AnalysisModel>[],
            ),
          )
          as _i18.Future<List<_i23.AnalysisModel>>);

  @override
  _i18.Future<_i6.HistoryPageModel> getHistoryPage(
    _i14.HistoryCriteria? criteria, {
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHistoryPage, [criteria], {#page: page}),
            returnValue: _i18.Future<_i6.HistoryPageModel>.value(
              _FakeHistoryPageModel_5(
                this,
                Invocation.method(#getHistoryPage, [criteria], {#page: page}),
              ),
            ),
          )
          as _i18.Future<_i6.HistoryPageModel>);
}

/// A class which mocks [PredictionRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPredictionRemoteDataSource extends _i1.Mock
    implements _i24.PredictionRemoteDataSource {
  MockPredictionRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i7.PredictionResultModel> predictImage(
    _i25.PredictionImageInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#predictImage, [input]),
            returnValue: _i18.Future<_i7.PredictionResultModel>.value(
              _FakePredictionResultModel_6(
                this,
                Invocation.method(#predictImage, [input]),
              ),
            ),
          )
          as _i18.Future<_i7.PredictionResultModel>);
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i26.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i8.UserProfileModel> updateProfile({
    String? fullName,
    String? medicalCenter,
    String? email,
    String? profession,
    String? specialty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #fullName: fullName,
              #medicalCenter: medicalCenter,
              #email: email,
              #profession: profession,
              #specialty: specialty,
            }),
            returnValue: _i18.Future<_i8.UserProfileModel>.value(
              _FakeUserProfileModel_7(
                this,
                Invocation.method(#updateProfile, [], {
                  #fullName: fullName,
                  #medicalCenter: medicalCenter,
                  #email: email,
                  #profession: profession,
                  #specialty: specialty,
                }),
              ),
            ),
          )
          as _i18.Future<_i8.UserProfileModel>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i27.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i9.AuthSession> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i18.Future<_i9.AuthSession>.value(
              _FakeAuthSession_8(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i18.Future<_i9.AuthSession>);

  @override
  _i18.Future<void> register({
    required String? fullName,
    required String? doctorId,
    String? medicalCenter,
    required String? email,
    required String? password,
    required String? profession,
    String? specialty,
    String? workspaceChoice,
    String? workspaceId,
    String? workspaceName,
    String? workspaceType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #fullName: fullName,
              #doctorId: doctorId,
              #medicalCenter: medicalCenter,
              #email: email,
              #password: password,
              #profession: profession,
              #specialty: specialty,
              #workspaceChoice: workspaceChoice,
              #workspaceId: workspaceId,
              #workspaceName: workspaceName,
              #workspaceType: workspaceType,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i10.AuthUser> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i18.Future<_i10.AuthUser>.value(
              _FakeAuthUser_9(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i18.Future<_i10.AuthUser>);

  @override
  _i18.Future<bool> hasSessionToken() =>
      (super.noSuchMethod(
            Invocation.method(#hasSessionToken, []),
            returnValue: _i18.Future<bool>.value(false),
          )
          as _i18.Future<bool>);

  @override
  _i18.Future<_i10.AuthUser?> getCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUser, []),
            returnValue: _i18.Future<_i10.AuthUser?>.value(),
          )
          as _i18.Future<_i10.AuthUser?>);

  @override
  _i18.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [AdminRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminRepository extends _i1.Mock implements _i28.AdminRepository {
  MockAdminRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<List<_i11.AdminUser>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i18.Future<List<_i11.AdminUser>>.value(
              <_i11.AdminUser>[],
            ),
          )
          as _i18.Future<List<_i11.AdminUser>>);

  @override
  _i18.Future<_i2.AdminPage<_i11.AdminUser>> getUsersPage(
    _i2.AdminQuery? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersPage, [query]),
            returnValue: _i18.Future<_i2.AdminPage<_i11.AdminUser>>.value(
              _FakeAdminPage_0<_i11.AdminUser>(
                this,
                Invocation.method(#getUsersPage, [query]),
              ),
            ),
          )
          as _i18.Future<_i2.AdminPage<_i11.AdminUser>>);

  @override
  _i18.Future<_i2.AdminPage<_i12.AdminWorkspaceRequest>> getCentersPage(
    _i2.AdminQuery? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCentersPage, [query]),
            returnValue:
                _i18.Future<_i2.AdminPage<_i12.AdminWorkspaceRequest>>.value(
                  _FakeAdminPage_0<_i12.AdminWorkspaceRequest>(
                    this,
                    Invocation.method(#getCentersPage, [query]),
                  ),
                ),
          )
          as _i18.Future<_i2.AdminPage<_i12.AdminWorkspaceRequest>>);

  @override
  _i18.Future<_i2.AdminPage<_i12.AdminMembershipRequest>> getAccessPage(
    _i2.AdminQuery? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAccessPage, [query]),
            returnValue:
                _i18.Future<_i2.AdminPage<_i12.AdminMembershipRequest>>.value(
                  _FakeAdminPage_0<_i12.AdminMembershipRequest>(
                    this,
                    Invocation.method(#getAccessPage, [query]),
                  ),
                ),
          )
          as _i18.Future<_i2.AdminPage<_i12.AdminMembershipRequest>>);

  @override
  _i18.Future<_i11.AdminUser> updateUserStatus({
    required int? userId,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserStatus, [], {
              #userId: userId,
              #status: status,
            }),
            returnValue: _i18.Future<_i11.AdminUser>.value(
              _FakeAdminUser_10(
                this,
                Invocation.method(#updateUserStatus, [], {
                  #userId: userId,
                  #status: status,
                }),
              ),
            ),
          )
          as _i18.Future<_i11.AdminUser>);

  @override
  _i18.Future<_i12.AdminSummary> getSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getSummary, []),
            returnValue: _i18.Future<_i12.AdminSummary>.value(
              _FakeAdminSummary_11(this, Invocation.method(#getSummary, [])),
            ),
          )
          as _i18.Future<_i12.AdminSummary>);

  @override
  _i18.Future<List<_i12.AdminWorkspaceRequest>> getWorkspaceRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceRequests, []),
            returnValue: _i18.Future<List<_i12.AdminWorkspaceRequest>>.value(
              <_i12.AdminWorkspaceRequest>[],
            ),
          )
          as _i18.Future<List<_i12.AdminWorkspaceRequest>>);

  @override
  _i18.Future<List<_i12.AdminMembershipRequest>> getMembershipRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipRequests, []),
            returnValue: _i18.Future<List<_i12.AdminMembershipRequest>>.value(
              <_i12.AdminMembershipRequest>[],
            ),
          )
          as _i18.Future<List<_i12.AdminMembershipRequest>>);

  @override
  _i18.Future<void> decideWorkspace(int? id, {required bool? approve}) =>
      (super.noSuchMethod(
            Invocation.method(#decideWorkspace, [id], {#approve: approve}),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i12.AdminWorkspaceRequest> updateCenter({
    required int? id,
    required String? city,
    required String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCenter, [], {
              #id: id,
              #city: city,
              #address: address,
            }),
            returnValue: _i18.Future<_i12.AdminWorkspaceRequest>.value(
              _FakeAdminWorkspaceRequest_12(
                this,
                Invocation.method(#updateCenter, [], {
                  #id: id,
                  #city: city,
                  #address: address,
                }),
              ),
            ),
          )
          as _i18.Future<_i12.AdminWorkspaceRequest>);

  @override
  _i18.Future<void> decideMembership(
    int? id, {
    required bool? approve,
    required String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #decideMembership,
              [id],
              {#approve: approve, #role: role},
            ),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [DashboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRepository extends _i1.Mock
    implements _i29.DashboardRepository {
  MockDashboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i13.DailySummary> getTodaySummary() =>
      (super.noSuchMethod(
            Invocation.method(#getTodaySummary, []),
            returnValue: _i18.Future<_i13.DailySummary>.value(
              _FakeDailySummary_13(
                this,
                Invocation.method(#getTodaySummary, []),
              ),
            ),
          )
          as _i18.Future<_i13.DailySummary>);
}

/// A class which mocks [HistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRepository extends _i1.Mock implements _i30.HistoryRepository {
  MockHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<List<_i31.Analysis>> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: _i18.Future<List<_i31.Analysis>>.value(
              <_i31.Analysis>[],
            ),
          )
          as _i18.Future<List<_i31.Analysis>>);

  @override
  _i18.Future<_i14.HistoryPage> getHistoryPage(
    _i14.HistoryCriteria? criteria, {
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHistoryPage, [criteria], {#page: page}),
            returnValue: _i18.Future<_i14.HistoryPage>.value(
              _FakeHistoryPage_14(
                this,
                Invocation.method(#getHistoryPage, [criteria], {#page: page}),
              ),
            ),
          )
          as _i18.Future<_i14.HistoryPage>);
}

/// A class which mocks [PredictionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPredictionRepository extends _i1.Mock
    implements _i32.PredictionRepository {
  MockPredictionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i15.PredictionResult> predictImage(
    _i25.PredictionImageInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#predictImage, [input]),
            returnValue: _i18.Future<_i15.PredictionResult>.value(
              _FakePredictionResult_15(
                this,
                Invocation.method(#predictImage, [input]),
              ),
            ),
          )
          as _i18.Future<_i15.PredictionResult>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i33.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i16.UserProfile> updateProfile({
    String? fullName,
    String? medicalCenter,
    String? email,
    String? profession,
    String? specialty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #fullName: fullName,
              #medicalCenter: medicalCenter,
              #email: email,
              #profession: profession,
              #specialty: specialty,
            }),
            returnValue: _i18.Future<_i16.UserProfile>.value(
              _FakeUserProfile_16(
                this,
                Invocation.method(#updateProfile, [], {
                  #fullName: fullName,
                  #medicalCenter: medicalCenter,
                  #email: email,
                  #profession: profession,
                  #specialty: specialty,
                }),
              ),
            ),
          )
          as _i18.Future<_i16.UserProfile>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i34.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i9.AuthSession> call({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #password: password}),
            returnValue: _i18.Future<_i9.AuthSession>.value(
              _FakeAuthSession_8(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i18.Future<_i9.AuthSession>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i35.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<void> call({
    required String? fullName,
    required String? doctorId,
    String? medicalCenter,
    required String? email,
    required String? password,
    required String? profession,
    String? specialty,
    String? workspaceChoice,
    String? workspaceId,
    String? workspaceName,
    String? workspaceType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #fullName: fullName,
              #doctorId: doctorId,
              #medicalCenter: medicalCenter,
              #email: email,
              #password: password,
              #profession: profession,
              #specialty: specialty,
              #workspaceChoice: workspaceChoice,
              #workspaceId: workspaceId,
              #workspaceName: workspaceName,
              #workspaceType: workspaceType,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i36.GetCurrentUserUseCase {
  MockGetCurrentUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i10.AuthUser> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i18.Future<_i10.AuthUser>.value(
              _FakeAuthUser_9(this, Invocation.method(#call, [])),
            ),
          )
          as _i18.Future<_i10.AuthUser>);
}

/// A class which mocks [GetCachedUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCachedUserUseCase extends _i1.Mock
    implements _i37.GetCachedUserUseCase {
  MockGetCachedUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i10.AuthUser?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i18.Future<_i10.AuthUser?>.value(),
          )
          as _i18.Future<_i10.AuthUser?>);
}

/// A class which mocks [HasSessionTokenUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockHasSessionTokenUseCase extends _i1.Mock
    implements _i38.HasSessionTokenUseCase {
  MockHasSessionTokenUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<bool> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i18.Future<bool>.value(false),
          )
          as _i18.Future<bool>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i39.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [UpdateProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfileUseCase extends _i1.Mock
    implements _i40.UpdateProfileUseCase {
  MockUpdateProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i16.UserProfile> call({
    String? fullName,
    String? medicalCenter,
    String? email,
    String? profession,
    String? specialty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #fullName: fullName,
              #medicalCenter: medicalCenter,
              #email: email,
              #profession: profession,
              #specialty: specialty,
            }),
            returnValue: _i18.Future<_i16.UserProfile>.value(
              _FakeUserProfile_16(
                this,
                Invocation.method(#call, [], {
                  #fullName: fullName,
                  #medicalCenter: medicalCenter,
                  #email: email,
                  #profession: profession,
                  #specialty: specialty,
                }),
              ),
            ),
          )
          as _i18.Future<_i16.UserProfile>);
}

/// A class which mocks [GetTodaySummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodaySummaryUseCase extends _i1.Mock
    implements _i41.GetTodaySummaryUseCase {
  MockGetTodaySummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i13.DailySummary> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i18.Future<_i13.DailySummary>.value(
              _FakeDailySummary_13(this, Invocation.method(#call, [])),
            ),
          )
          as _i18.Future<_i13.DailySummary>);
}

/// A class which mocks [GetHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHistoryUseCase extends _i1.Mock implements _i42.GetHistoryUseCase {
  MockGetHistoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<List<_i31.Analysis>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i18.Future<List<_i31.Analysis>>.value(
              <_i31.Analysis>[],
            ),
          )
          as _i18.Future<List<_i31.Analysis>>);
}

/// A class which mocks [PredictImageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPredictImageUseCase extends _i1.Mock
    implements _i43.PredictImageUseCase {
  MockPredictImageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i15.PredictionResult> call(_i25.PredictionImageInput? input) =>
      (super.noSuchMethod(
            Invocation.method(#call, [input]),
            returnValue: _i18.Future<_i15.PredictionResult>.value(
              _FakePredictionResult_15(this, Invocation.method(#call, [input])),
            ),
          )
          as _i18.Future<_i15.PredictionResult>);
}

/// A class which mocks [GetAdminUsersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAdminUsersUseCase extends _i1.Mock
    implements _i44.GetAdminUsersUseCase {
  MockGetAdminUsersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<List<_i11.AdminUser>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i18.Future<List<_i11.AdminUser>>.value(
              <_i11.AdminUser>[],
            ),
          )
          as _i18.Future<List<_i11.AdminUser>>);
}

/// A class which mocks [UpdateAdminUserStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateAdminUserStatusUseCase extends _i1.Mock
    implements _i45.UpdateAdminUserStatusUseCase {
  MockUpdateAdminUserStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i11.AdminUser> call({
    required int? userId,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#userId: userId, #status: status}),
            returnValue: _i18.Future<_i11.AdminUser>.value(
              _FakeAdminUser_10(
                this,
                Invocation.method(#call, [], {
                  #userId: userId,
                  #status: status,
                }),
              ),
            ),
          )
          as _i18.Future<_i11.AdminUser>);
}
