// Mocks generated by Mockito 5.4.6 from annotations
// in bucalscan_ai/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:bucalscan_ai/data/services/auth_storage_service.dart' as _i14;
import 'package:bucalscan_ai/features/admin/data/datasources/admin_remote_datasource.dart'
    as _i15;
import 'package:bucalscan_ai/features/admin/data/models/admin_user_model.dart'
    as _i2;
import 'package:bucalscan_ai/features/admin/domain/entities/admin_user.dart'
    as _i8;
import 'package:bucalscan_ai/features/admin/domain/repositories/admin_repository.dart'
    as _i23;
import 'package:bucalscan_ai/features/admin/domain/usecases/get_admin_users_usecase.dart'
    as _i39;
import 'package:bucalscan_ai/features/admin/domain/usecases/update_admin_user_status_usecase.dart'
    as _i40;
import 'package:bucalscan_ai/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i12;
import 'package:bucalscan_ai/features/auth/domain/entities/auth_session.dart'
    as _i6;
import 'package:bucalscan_ai/features/auth/domain/entities/auth_user.dart'
    as _i7;
import 'package:bucalscan_ai/features/auth/domain/repositories/auth_repository.dart'
    as _i22;
import 'package:bucalscan_ai/features/auth/domain/usecases/get_cached_user_usecase.dart'
    as _i32;
import 'package:bucalscan_ai/features/auth/domain/usecases/get_current_user_usecase.dart'
    as _i31;
import 'package:bucalscan_ai/features/auth/domain/usecases/has_session_token_usecase.dart'
    as _i33;
import 'package:bucalscan_ai/features/auth/domain/usecases/login_usecase.dart'
    as _i29;
import 'package:bucalscan_ai/features/auth/domain/usecases/logout_usecase.dart'
    as _i34;
import 'package:bucalscan_ai/features/auth/domain/usecases/register_usecase.dart'
    as _i30;
import 'package:bucalscan_ai/features/dashboard/data/datasources/dashboard_remote_datasource.dart'
    as _i16;
import 'package:bucalscan_ai/features/dashboard/data/models/daily_summary_model.dart'
    as _i3;
import 'package:bucalscan_ai/features/dashboard/domain/entities/daily_summary.dart'
    as _i9;
import 'package:bucalscan_ai/features/dashboard/domain/repositories/dashboard_repository.dart'
    as _i24;
import 'package:bucalscan_ai/features/dashboard/domain/usecases/get_today_summary_usecase.dart'
    as _i36;
import 'package:bucalscan_ai/features/history/data/datasources/history_remote_datasource.dart'
    as _i17;
import 'package:bucalscan_ai/features/history/data/models/analysis_model.dart'
    as _i18;
import 'package:bucalscan_ai/features/history/domain/entities/analysis.dart'
    as _i26;
import 'package:bucalscan_ai/features/history/domain/repositories/history_repository.dart'
    as _i25;
import 'package:bucalscan_ai/features/history/domain/usecases/get_history_usecase.dart'
    as _i37;
import 'package:bucalscan_ai/features/prediction/data/datasources/prediction_remote_datasource.dart'
    as _i19;
import 'package:bucalscan_ai/features/prediction/data/models/prediction_result_model.dart'
    as _i4;
import 'package:bucalscan_ai/features/prediction/domain/entities/prediction_image_input.dart'
    as _i20;
import 'package:bucalscan_ai/features/prediction/domain/entities/prediction_result.dart'
    as _i10;
import 'package:bucalscan_ai/features/prediction/domain/repositories/prediction_repository.dart'
    as _i27;
import 'package:bucalscan_ai/features/prediction/domain/usecases/predict_image_usecase.dart'
    as _i38;
import 'package:bucalscan_ai/features/profile/data/datasources/profile_remote_datasource.dart'
    as _i21;
import 'package:bucalscan_ai/features/profile/data/models/user_profile_model.dart'
    as _i5;
import 'package:bucalscan_ai/features/profile/domain/entities/user_profile.dart'
    as _i11;
import 'package:bucalscan_ai/features/profile/domain/repositories/profile_repository.dart'
    as _i28;
import 'package:bucalscan_ai/features/profile/domain/usecases/update_profile_usecase.dart'
    as _i35;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAdminUserModel_0 extends _i1.SmartFake
    implements _i2.AdminUserModel {
  _FakeAdminUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDailySummaryModel_1 extends _i1.SmartFake
    implements _i3.DailySummaryModel {
  _FakeDailySummaryModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePredictionResultModel_2 extends _i1.SmartFake
    implements _i4.PredictionResultModel {
  _FakePredictionResultModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfileModel_3 extends _i1.SmartFake
    implements _i5.UserProfileModel {
  _FakeUserProfileModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthSession_4 extends _i1.SmartFake implements _i6.AuthSession {
  _FakeAuthSession_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthUser_5 extends _i1.SmartFake implements _i7.AuthUser {
  _FakeAuthUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminUser_6 extends _i1.SmartFake implements _i8.AdminUser {
  _FakeAdminUser_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDailySummary_7 extends _i1.SmartFake implements _i9.DailySummary {
  _FakeDailySummary_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePredictionResult_8 extends _i1.SmartFake
    implements _i10.PredictionResult {
  _FakePredictionResult_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfile_9 extends _i1.SmartFake implements _i11.UserProfile {
  _FakeUserProfile_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i12.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<Map<String, dynamic>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i13.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i13.Future<Map<String, dynamic>>);

  @override
  _i13.Future<Map<String, dynamic>> register({
    required String? fullName,
    required String? doctorId,
    String? medicalCenter,
    required String? email,
    required String? password,
    required String? profession,
    String? specialty,
    String? workspaceChoice,
    String? workspaceId,
    String? workspaceName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #fullName: fullName,
              #doctorId: doctorId,
              #medicalCenter: medicalCenter,
              #email: email,
              #password: password,
              #profession: profession,
              #specialty: specialty,
              #workspaceChoice: workspaceChoice,
              #workspaceId: workspaceId,
              #workspaceName: workspaceName,
            }),
            returnValue: _i13.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i13.Future<Map<String, dynamic>>);

  @override
  _i13.Future<Map<String, dynamic>> me() =>
      (super.noSuchMethod(
            Invocation.method(#me, []),
            returnValue: _i13.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i13.Future<Map<String, dynamic>>);
}

/// A class which mocks [AuthStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStorageService extends _i1.Mock
    implements _i14.AuthStorageService {
  MockAuthStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);

  @override
  _i13.Future<void> removeToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeToken, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> saveUserJson(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserJson, [userData]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<Map<String, dynamic>?> getUserJson() =>
      (super.noSuchMethod(
            Invocation.method(#getUserJson, []),
            returnValue: _i13.Future<Map<String, dynamic>?>.value(),
          )
          as _i13.Future<Map<String, dynamic>?>);

  @override
  _i13.Future<void> removeUserJson() =>
      (super.noSuchMethod(
            Invocation.method(#removeUserJson, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [AdminRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminRemoteDataSource extends _i1.Mock
    implements _i15.AdminRemoteDataSource {
  MockAdminRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i2.AdminUserModel>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i13.Future<List<_i2.AdminUserModel>>.value(
              <_i2.AdminUserModel>[],
            ),
          )
          as _i13.Future<List<_i2.AdminUserModel>>);

  @override
  _i13.Future<_i2.AdminUserModel> updateUserStatus({
    required int? userId,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserStatus, [], {
              #userId: userId,
              #status: status,
            }),
            returnValue: _i13.Future<_i2.AdminUserModel>.value(
              _FakeAdminUserModel_0(
                this,
                Invocation.method(#updateUserStatus, [], {
                  #userId: userId,
                  #status: status,
                }),
              ),
            ),
          )
          as _i13.Future<_i2.AdminUserModel>);
}

/// A class which mocks [DashboardRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRemoteDataSource extends _i1.Mock
    implements _i16.DashboardRemoteDataSource {
  MockDashboardRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i3.DailySummaryModel> getTodaySummary() =>
      (super.noSuchMethod(
            Invocation.method(#getTodaySummary, []),
            returnValue: _i13.Future<_i3.DailySummaryModel>.value(
              _FakeDailySummaryModel_1(
                this,
                Invocation.method(#getTodaySummary, []),
              ),
            ),
          )
          as _i13.Future<_i3.DailySummaryModel>);
}

/// A class which mocks [HistoryRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRemoteDataSource extends _i1.Mock
    implements _i17.HistoryRemoteDataSource {
  MockHistoryRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i18.AnalysisModel>> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: _i13.Future<List<_i18.AnalysisModel>>.value(
              <_i18.AnalysisModel>[],
            ),
          )
          as _i13.Future<List<_i18.AnalysisModel>>);
}

/// A class which mocks [PredictionRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPredictionRemoteDataSource extends _i1.Mock
    implements _i19.PredictionRemoteDataSource {
  MockPredictionRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i4.PredictionResultModel> predictImage(
    _i20.PredictionImageInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#predictImage, [input]),
            returnValue: _i13.Future<_i4.PredictionResultModel>.value(
              _FakePredictionResultModel_2(
                this,
                Invocation.method(#predictImage, [input]),
              ),
            ),
          )
          as _i13.Future<_i4.PredictionResultModel>);
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i21.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i5.UserProfileModel> updateProfile({
    String? fullName,
    String? medicalCenter,
    String? email,
    String? profession,
    String? specialty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #fullName: fullName,
              #medicalCenter: medicalCenter,
              #email: email,
              #profession: profession,
              #specialty: specialty,
            }),
            returnValue: _i13.Future<_i5.UserProfileModel>.value(
              _FakeUserProfileModel_3(
                this,
                Invocation.method(#updateProfile, [], {
                  #fullName: fullName,
                  #medicalCenter: medicalCenter,
                  #email: email,
                  #profession: profession,
                  #specialty: specialty,
                }),
              ),
            ),
          )
          as _i13.Future<_i5.UserProfileModel>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i22.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i6.AuthSession> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i13.Future<_i6.AuthSession>.value(
              _FakeAuthSession_4(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i13.Future<_i6.AuthSession>);

  @override
  _i13.Future<void> register({
    required String? fullName,
    required String? doctorId,
    String? medicalCenter,
    required String? email,
    required String? password,
    required String? profession,
    String? specialty,
    String? workspaceChoice,
    String? workspaceId,
    String? workspaceName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #fullName: fullName,
              #doctorId: doctorId,
              #medicalCenter: medicalCenter,
              #email: email,
              #password: password,
              #profession: profession,
              #specialty: specialty,
              #workspaceChoice: workspaceChoice,
              #workspaceId: workspaceId,
              #workspaceName: workspaceName,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i7.AuthUser> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i13.Future<_i7.AuthUser>.value(
              _FakeAuthUser_5(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i13.Future<_i7.AuthUser>);

  @override
  _i13.Future<bool> hasSessionToken() =>
      (super.noSuchMethod(
            Invocation.method(#hasSessionToken, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<_i7.AuthUser?> getCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUser, []),
            returnValue: _i13.Future<_i7.AuthUser?>.value(),
          )
          as _i13.Future<_i7.AuthUser?>);

  @override
  _i13.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [AdminRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminRepository extends _i1.Mock implements _i23.AdminRepository {
  MockAdminRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i8.AdminUser>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i13.Future<List<_i8.AdminUser>>.value(
              <_i8.AdminUser>[],
            ),
          )
          as _i13.Future<List<_i8.AdminUser>>);

  @override
  _i13.Future<_i8.AdminUser> updateUserStatus({
    required int? userId,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserStatus, [], {
              #userId: userId,
              #status: status,
            }),
            returnValue: _i13.Future<_i8.AdminUser>.value(
              _FakeAdminUser_6(
                this,
                Invocation.method(#updateUserStatus, [], {
                  #userId: userId,
                  #status: status,
                }),
              ),
            ),
          )
          as _i13.Future<_i8.AdminUser>);
}

/// A class which mocks [DashboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRepository extends _i1.Mock
    implements _i24.DashboardRepository {
  MockDashboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i9.DailySummary> getTodaySummary() =>
      (super.noSuchMethod(
            Invocation.method(#getTodaySummary, []),
            returnValue: _i13.Future<_i9.DailySummary>.value(
              _FakeDailySummary_7(
                this,
                Invocation.method(#getTodaySummary, []),
              ),
            ),
          )
          as _i13.Future<_i9.DailySummary>);
}

/// A class which mocks [HistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRepository extends _i1.Mock implements _i25.HistoryRepository {
  MockHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i26.Analysis>> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: _i13.Future<List<_i26.Analysis>>.value(
              <_i26.Analysis>[],
            ),
          )
          as _i13.Future<List<_i26.Analysis>>);
}

/// A class which mocks [PredictionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPredictionRepository extends _i1.Mock
    implements _i27.PredictionRepository {
  MockPredictionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i10.PredictionResult> predictImage(
    _i20.PredictionImageInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#predictImage, [input]),
            returnValue: _i13.Future<_i10.PredictionResult>.value(
              _FakePredictionResult_8(
                this,
                Invocation.method(#predictImage, [input]),
              ),
            ),
          )
          as _i13.Future<_i10.PredictionResult>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i28.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i11.UserProfile> updateProfile({
    String? fullName,
    String? medicalCenter,
    String? email,
    String? profession,
    String? specialty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #fullName: fullName,
              #medicalCenter: medicalCenter,
              #email: email,
              #profession: profession,
              #specialty: specialty,
            }),
            returnValue: _i13.Future<_i11.UserProfile>.value(
              _FakeUserProfile_9(
                this,
                Invocation.method(#updateProfile, [], {
                  #fullName: fullName,
                  #medicalCenter: medicalCenter,
                  #email: email,
                  #profession: profession,
                  #specialty: specialty,
                }),
              ),
            ),
          )
          as _i13.Future<_i11.UserProfile>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i29.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i6.AuthSession> call({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #password: password}),
            returnValue: _i13.Future<_i6.AuthSession>.value(
              _FakeAuthSession_4(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i13.Future<_i6.AuthSession>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i30.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> call({
    required String? fullName,
    required String? doctorId,
    String? medicalCenter,
    required String? email,
    required String? password,
    required String? profession,
    String? specialty,
    String? workspaceChoice,
    String? workspaceId,
    String? workspaceName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #fullName: fullName,
              #doctorId: doctorId,
              #medicalCenter: medicalCenter,
              #email: email,
              #password: password,
              #profession: profession,
              #specialty: specialty,
              #workspaceChoice: workspaceChoice,
              #workspaceId: workspaceId,
              #workspaceName: workspaceName,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i31.GetCurrentUserUseCase {
  MockGetCurrentUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i7.AuthUser> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<_i7.AuthUser>.value(
              _FakeAuthUser_5(this, Invocation.method(#call, [])),
            ),
          )
          as _i13.Future<_i7.AuthUser>);
}

/// A class which mocks [GetCachedUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCachedUserUseCase extends _i1.Mock
    implements _i32.GetCachedUserUseCase {
  MockGetCachedUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i7.AuthUser?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<_i7.AuthUser?>.value(),
          )
          as _i13.Future<_i7.AuthUser?>);
}

/// A class which mocks [HasSessionTokenUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockHasSessionTokenUseCase extends _i1.Mock
    implements _i33.HasSessionTokenUseCase {
  MockHasSessionTokenUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<bool> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i34.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [UpdateProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfileUseCase extends _i1.Mock
    implements _i35.UpdateProfileUseCase {
  MockUpdateProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i11.UserProfile> call({
    String? fullName,
    String? medicalCenter,
    String? email,
    String? profession,
    String? specialty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #fullName: fullName,
              #medicalCenter: medicalCenter,
              #email: email,
              #profession: profession,
              #specialty: specialty,
            }),
            returnValue: _i13.Future<_i11.UserProfile>.value(
              _FakeUserProfile_9(
                this,
                Invocation.method(#call, [], {
                  #fullName: fullName,
                  #medicalCenter: medicalCenter,
                  #email: email,
                  #profession: profession,
                  #specialty: specialty,
                }),
              ),
            ),
          )
          as _i13.Future<_i11.UserProfile>);
}

/// A class which mocks [GetTodaySummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodaySummaryUseCase extends _i1.Mock
    implements _i36.GetTodaySummaryUseCase {
  MockGetTodaySummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i9.DailySummary> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<_i9.DailySummary>.value(
              _FakeDailySummary_7(this, Invocation.method(#call, [])),
            ),
          )
          as _i13.Future<_i9.DailySummary>);
}

/// A class which mocks [GetHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHistoryUseCase extends _i1.Mock implements _i37.GetHistoryUseCase {
  MockGetHistoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i26.Analysis>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<List<_i26.Analysis>>.value(
              <_i26.Analysis>[],
            ),
          )
          as _i13.Future<List<_i26.Analysis>>);
}

/// A class which mocks [PredictImageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPredictImageUseCase extends _i1.Mock
    implements _i38.PredictImageUseCase {
  MockPredictImageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i10.PredictionResult> call(_i20.PredictionImageInput? input) =>
      (super.noSuchMethod(
            Invocation.method(#call, [input]),
            returnValue: _i13.Future<_i10.PredictionResult>.value(
              _FakePredictionResult_8(this, Invocation.method(#call, [input])),
            ),
          )
          as _i13.Future<_i10.PredictionResult>);
}

/// A class which mocks [GetAdminUsersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAdminUsersUseCase extends _i1.Mock
    implements _i39.GetAdminUsersUseCase {
  MockGetAdminUsersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i8.AdminUser>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i13.Future<List<_i8.AdminUser>>.value(
              <_i8.AdminUser>[],
            ),
          )
          as _i13.Future<List<_i8.AdminUser>>);
}

/// A class which mocks [UpdateAdminUserStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateAdminUserStatusUseCase extends _i1.Mock
    implements _i40.UpdateAdminUserStatusUseCase {
  MockUpdateAdminUserStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i8.AdminUser> call({
    required int? userId,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#userId: userId, #status: status}),
            returnValue: _i13.Future<_i8.AdminUser>.value(
              _FakeAdminUser_6(
                this,
                Invocation.method(#call, [], {
                  #userId: userId,
                  #status: status,
                }),
              ),
            ),
          )
          as _i13.Future<_i8.AdminUser>);
}
